version: '3'
services:
  filmshelf:
    command: npm start
    environment:
    - NODE_ENV=production
    ports:
      - "80:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: filmshelf
        awslogs-region: us-east-1
        awslogs-stream-prefix: filmshelf
    image: mimsy/filmshelf
    restart: always
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
