version: '3'
services:
  filmshelf:
    build: .
    restart: always
    depends_on:
    - mongo
    command: npm run test && nyc report --reporter=text-lcov | coveralls
    volumes:
    - ./src:/app/src
    - ./test:/app/test
    - ./tsconfig.json:/app/tsconfig.json
    environment:
    - NODE_ENV=test
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"