version: '3'
services:
  filmshelf:
    build: .
    volumes:
    - ./src:/app/src
    ports:
      - "80:3000"
    restart: always
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"